name: Deploy

on:
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.16.x ]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test -v ./...

  build:
    needs: [ test ]
    if: success()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "riyadattani"
          heroku_email: "riya_dattani@hotmail.com"
          usedocker: true